config/routes.rb
Rails.application.routes.draw do
  # We need to be tricky here or Devise loads up the defaults again.
  devise_for :user_authentications, 
             :skip => [:registrations, :unlocks],
             :controllers => {:passwords => "user_passwords",
                              :sessions => "user_sessions",
                              :omniauth_callbacks => "omniauth_callbacks" } do
    post "merge", :to => "user_sessions#merge", :as => "merge_user"
  end

  resources :user_authentications
  
  match 'account' => 'users#show', :as => 'user_root'
  
  namespace :admin do
    resources :authentication_methods
  end
  
end

app/models/authentication_method.rb
class AuthenticationMethod < ActiveRecord::Base
  
  preference :provider, :string
  preference :api_key, :string
  preference :api_secret, :string
  preference :environment, :string

  #after_save :reset_devise
  #
  #private
  #
  #def reset_devise
  #  logger.debug("Self: #{self.environment}\nRails: #{RAILS_ENV}")
  #  if (self.environment == RAILS_ENV)
  #    SpreeSocial.reset_key_for(self.preferred_provider,self.preferred_api_key, self.preferred_api_secret)
  #  end
  #end
  
end

app/models/social_ability.rb
class SocialAbility
# stuff like class AbilityDecorator goes here
  include CanCan::Ability

  def initialize(user)

    can :create, UserAuthentication do
      !user.new_record?
    end

    can :destroy, UserAuthentication do |user_authentication|
      user_authentication.user == user
    end

    can :read, User do |resource, token|
      resource == user || resource.token && token == resource.token
    end

    can :update, User do |resource, token|
      resource == user || resource.token && token == resource.token
    end
  end
end

app/models/user_authentication.rb
class UserAuthentication < ActiveRecord::Base
  
  belongs_to :user
  
  # Lock down authentications to a non-destructive account and login via association
  devise :omniauthable

end

app/models/user_decorator.rb
User.class_eval do
  token_resource

  has_many :user_authentications

  # Associates user to auth source
  def associate_auth(source)
    return if user_authentications.where(:provider => source['provider'], :uid => source['uid'].to_s).count > 0
    self.user_authentications.create!(:provider => source['provider'], :uid => source['uid'], :nickname => source["user_info"]['nickname'])
  end

  # Thx Ryan
  def password_required?
    (user_authentications.empty? || !password.blank?) && super
  end

end

app/controllers/admin/authentication_methods_controller.rb
class Admin::AuthenticationMethodsController < Admin::BaseController
  resource_controller

  update.wants.html { redirect_to collection_url }
  create.wants.html { redirect_to collection_url }

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  include Spree::CurrentOrder
  include SpreeBase
  helper :users, 'spree/base'


  SpreeSocial::OAUTH_PROVIDERS.each do |provider|
    method_name = (provider[1]).to_sym
    send :define_method, method_name do
      social_setup(provider[0])
    end
  end

  def failure
    set_flash_message :alert, :failure, :kind => failed_strategy.name.to_s.humanize, :reason => failure_message
    redirect_to after_omniauth_failure_path_for(:user)
  end
 
  private

  def social_setup(provider)
    omniauth = request.env["omniauth.auth"]

    if request.env["omniauth.error"].present?
      flash[:error] = t("devise.omniauth_callbacks.failure", :kind => provider, :reason => "user was not valid")
      redirect_back_or_default(root_url)
      return
    end

    existing_auth = UserAuthentication.where(:provider => omniauth['provider'], :uid => omniauth['uid'].to_s).first

    #signing back in from a social source
    if existing_auth
      user = existing_auth.user
    else # adding a social source
      user = current_user
    end

    user ||= User.anonymous!

    user.associate_auth(omniauth) unless existing_auth

    if current_order
      current_order.associate_user!(user)
      session[:guest_token] = nil
    end

    if user.anonymous?
      session[:user_access_token] = user.token #set user access token so we can edit this user again later

      flash.now[:notice] = t("one_more_step", :kind => omniauth['provider'].capitalize)
      render(:template => "user_registrations/social_edit", :locals => {:user => user, :omniauth => omniauth})
    elsif current_user
      flash[:error] = t("attach_error", :kind => omniauth['provider'].capitalize) if existing_auth && (existing_auth.user != current_user)
      redirect_back_or_default(account_url)
    else
      sign_in_and_redirect(user, :event => :authentication)
    end
  end

end

app/controllers/user_authentications_controller.rb
#encoding: utf-8
class UserAuthenticationsController < Spree::BaseController

  def update
    @user = User.find(params[:id])

    authorize! :edit, @user, session[:user_access_token]

    session[:user_access_token] = nil

    @user.email = params[:user][:email]
    if @user.save
      sign_in(@user, :event => :authentication) unless current_user
      redirect_back_or_default(products_path)
    else
      flash.now[:error] = "Данный email уже зарегистрирован. Необходимо авторизоваться, чтобы связать ваш аккаунт на сайте и аккаунт в социальной сети."
      render(:template => 'users/merge')
    end
  end

  def destroy
    @auth = current_user.user_authentications.find(params[:id])

    authorize! :destroy, @auth

    @auth.destroy
    flash[:notice] = "Successfully deleted authentication source."
    redirect_to account_path
  end
end

app/controllers/user_registrations_controller_decorator.rb
UserRegistrationsController.class_eval do

  def create
    super.tap do |resp|
      if @user && @user.new_record? && resp.respond_to?(:session)
        @omniauth = resp.session[:session]
        resp.session[:omniauth] = nil unless @user.new_record?
      end
    end
  end

  def delete
    session[:omniauth] = nil
    redirect_to signin_path
  end

end

app/controllers/user_sessions_controller_decorator.rb
UserSessionsController.class_eval do

  def merge
    # now sign in from the login form
    authenticate_user!

    if not current_user
      flash[:error] = I18n.t("devise.failure.invalid")
      @user = User.find(params['user']['id'])
      return render(:template => 'users/merge')
    end

    # prep for all the shifting and do it
    user = User.find(current_user.id)
    user.user_authentications << UserAuthentication.find(params[:user_authentication])
    user.save!

    if current_order
      current_order.associate_user!(user)
      session[:guest_token] = nil
    end
    # trash the old anonymous that was created
    User.destroy(params[:user][:id])

    # tell the truth now
    flash[:alert] = "Succesfully linked your accounts"
    sign_in_and_redirect(user, :event => :authentication)
  end

end

app/views/admin/authentication_methods/_form.html.erb
<div class="yui-g">
  <div class="yui-u first">
      <p>
        <label><%=t("environment")%></label>
        <br/>
        <%= f.collection_select(:environment,
                                Configuration.configurations.keys.sort,
                                :to_s, :titleize,
                                {}, {:id => "gtwy-env"}) %>
      </p>

      <p>
        <%= f.check_box :active, {:style => "vertical-align:middle;"} %>
        <label>
          <%= t('social_enable_provider') %>
        </label>
      </p>

      <p>
        <label><%= t('social_provider') %></label><br />
        <%= f.select :preferred_provider, SpreeSocial::OAUTH_PROVIDERS, {:include_blank => true} %>
        <br/>
        <span class="info">
          <%= t("social_provider") %>
        </span>
      </p>

      <p>
        <label><%= t('social_api_key') %></label><br />
        <%= f.text_field :preferred_api_key, :size => 40, :maxlength => 256 %>
        <br/>
        <span class="info">
          <%= t("social_api_key") %>
        </span>
      </p>

      <p>
        <label><%= t('social_api_secret') %></label><br />
        <%= f.text_field :preferred_api_secret, :size => 40, :maxlength => 256 %>
        <br/>
        <span class="info">
          <%= t("social_api_secret") %>
        </span>
      </p>

    </fieldset>

  </div>
</div>

app/views/admin/authentication_methods/edit.html.erb
<%= render :partial => 'admin/shared/configuration_menu' %>

<h1><%= t("edit_social_method") %></h1>
<h4><%= t("edit_social_method_warning") %></h4>
<%= render 'shared/error_messages', :target => @authentication_method %>

<%= form_for(:authentication_method, :url => admin_authentication_method_path(@authentication_method), :html => {:method => :put}) do |f| %>
  <%= render :partial => "form", :locals => { :f => f } %>
  <p class="form-buttons"><%= button t("edit") %></p>
<% end %>

app/views/admin/authentication_methods/index.html.erb
<%= render :partial => 'admin/shared/configuration_menu' %>

<div class='toolbar'>
  <ul class='actions'>
    <li>
      <%= button_link_to t("new_social_method"), new_object_url, :icon => 'add'  %>
    </li>
  </ul>
  <br class='clear' />
</div>

<h1><%= t("social_methods") %></h1>

<table class="index">
  <thead>
    <%= hook :admin_social_methods_index_headers do %>
      <th><%= t("provider") %></th>
      <th><%= t("social_api_key") %></th>
      <th><%= t("social_api_secret") %></th>
      <th><%= t("environment") %></th>
      <th><%= t("active") %></th>
    <% end %>
    <th>
      <%= hook :admin_social_methods_index_header_actions %>
    </th>
  </thead>
  <tbody>
    <% @authentication_methods.each do |method|%>
      <tr id="<%= dom_id method %>">     
        <%- locals = {:method => method} %>
        <%= hook :admin_trackers_index_rows, locals do %>        
          <td><%= method.preferred_provider %></td>
          <td><%= method.preferred_api_key %></td>
          <td><%= method.preferred_api_secret %></td>
          <td><%= method.environment.to_s.titleize %></td>
          <td><%= method.active ? t(:yes) : t(:no) %></td>
        <% end %>
        <td>
        	<%= link_to_edit method %> &nbsp;
        	<%= link_to_delete method %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/authentication_methods/new.html.erb
<%= render :partial => 'admin/shared/configuration_menu' %>

<h1><%= t("new_social_method") %></h1>
<h4><%= t("new_social_method_warning") %></h4>
<%= render 'shared/error_messages', :target => @authentication_method %>

<%= form_for(:authentication_method, :url => collection_url) do |f| %>
  <%= render :partial => "form", :locals => { :f => f } %>
  <p class="form-buttons"><%= button t("create") %></p>
<% end %>

app/views/admin/shared/_configurations_menu.html.erb
<tr>
  <td><%= link_to t("social_servers"), admin_authentication_methods_path %></td>
  <td><%= t("social_servers_description") %></td>
</tr>

app/views/admin/shared/_sidebar_menu.html.erb
<li<%= raw(' class="active"') if controller.controller_name == 'authentication_methods' %>><%= link_to t("social_servers"), admin_authentication_methods_path %></li>

app/views/shared/_socials.html.erb
<% if !current_user || !current_user.user_authentications %>
  <h2>Sign in through one of these services:</h2>
<% end %>
<% AuthenticationMethod.where(:environment => ::Rails.env).each do |user| %>
  <%- img = File.exist?(::Rails.root+"public/images/social/#{user.preferred_provider}_32.png") ? "social/#{user.preferred_provider}_32.png" : "social/spree_32.png" -%>
  <%= link_to(image_tag(img, :size => "32x32", :alt => "#{user.preferred_provider}"), user_authentication_omniauth_authorize_path(user.preferred_provider.to_sym), :title => "Sign in with #{user.preferred_provider}") if user.active %>
<% end %>

app/views/user_registrations/new.html.erb
<% @body_id = 'signup' %>

<%= render "shared/error_messages", :target => @user %>

<div id="new-customer">
  <h2><%= t("new_customer") %></h2>

  <%= hook :signup do %>

    <%= form_for(:user, :url => registration_path(@user)) do |f| %>

      <%= hook :signup_inside_form do %>
        <% if session[:omniauth] %>
          <p>
            <%= f.label :email, t("email") %><br />
            <%= f.text_field :email, :class => 'title'  %>
          </p>
          <p><%= submit_tag t("create"), :class => 'button primary' %></p>
        <% else %>
          <%= render 'shared/user_form', :f => f %>
          <p><%= submit_tag t("create"), :class => 'button primary' %></p>
        <% end %>
      <% end %>

    <% end %>
    <%= t("or") %> <%= session[:omniauth] ? link_to( t("login_as_existing"), user_registration_path, :method => :delete) : link_to( t("login_as_existing"), login_path) %>
  <% end %>

</div>

app/views/user_registrations/social_edit.html.erb
<div id="existing-customer">
  <table>
    <tr>
      <% if user.anonymous? %>
        <%= form_for(:user, :url => user_authentication_path(user), :html => { :method => :put }) do |f| %>
          <td><%= f.label :email, t("email") %></td>
          <td><%= f.text_field :email, :class => 'title', :value => (omniauth["extra"]["user_hash"]["email"] unless omniauth.nil? ) %></td>
          <td><%=submit_tag t("update") %></td>
        <% end %>
      <% else %>
        <td><%= t("email") %>:</td>
        <td>
          <%= user.email %>
        </td>
        <td><p><%= link_to t('edit'), edit_account_path %></p></td>
      <% end %>
    </tr>
  </table>

app/views/users/_social.html.erb
<% @body_id = 'login' %>
<div id="existing-customer">
  <table>
    <tr>
      <% if @user.anonymous? %>
        <%= render :partial => 'shared/social_registrations', :locals => {:user => @user, :omniauth => @omniauth} %>
      <% else %>
      <td><%= t("email") %>:</td>
      <td>
        <%= @user.email %>
      </td>
      <td><p><%= link_to t('edit'), edit_account_path %></p></td>
      <% end %>
    </tr>
  </table>

<% if @user.user_authentications %>
  <% unless @user.user_authentications.empty? %>
    <p><strong>You have signed in with these services:</strong></p>
    <div class="authentications">
      <% for user_authentication in @user.user_authentications %>
        <div class="authentication">
          <%= image_tag File.exist?(::Rails.root+"public/images/social/#{user_authentication.provider}_32.png") ? "social/#{user_authentication.provider}_32.png" : "social/spree_32.png", :size => "32x32" %>
          <div class="provider"><%= user_authentication.provider %></div>
          <div class="uid"><%= user_authentication.nickname %></div>
          <%= link_to( "X", user_authentication, :confirm => 'Are you sure you want to remove this authentication option?', :method => :delete, :class => "remove") %>
        </div>
      <% end %>
      <div class="clear"></div>
    </div>
  <% end %>
</div>
  <p><strong>Add another service to sign in with:</strong></p>
<% end %>

<%= hook :login_extras %>

<div class="clear"></div>

<% content_for :head do %>
  <%= stylesheet_link_tag 'social.css' %>  
<% end %>

app/views/users/merge.html.erb
<% @body_id = 'login' %>
<div id="existing-customer">
  <h2><%= t("login_as_existing") %></h2>
  <%= form_for(:user, :url => merge_user_path) do |f| %>
    <%= hidden_field_tag(:user_authentication, @user.user_authentications.first.id) %>
    <%= f.hidden_field(:id) %>
    <div id='password-credentials'>
      <p>
        <%= f.label(:email, t("email")) %><br />
        <%= f.text_field('email', :class => 'title') %>
      </p>
      <p>
        <%= f.label :password, t("password") %><br />
        <%= f.password_field 'password', :class => 'title' %>
      </p>
    </div>
  <p><%= submit_tag t("log_in"), :class => 'button primary'%></p>
  <%= link_to t("forgot_password"), new_user_password_path %>
  <% end %>
</div>